name: Tests
on:
  workflow_call:
jobs:
  missing-includes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for missing includes
        run: |
          python3 .github/scripts/tests/check-includes.py
  check-lang-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for missing language keys
        run: |
          python3 .github/scripts/tests/check-lang-keys.py ./lang